---
# tasks to install essential apt packages
#
# - git: sourcecode version control
#
- name: Install essential packages
  sudo: yes
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    #  error in debian 7
    #  - epel-release
    - git
