---
- name: Install nginx
  sudo: yes
  yum:
    name: nginx
    update_cache: yes
  tags: nginx


- name: Change permission of /var/log/nginx/
  sudo: yes
  file:
    state: directory
    path: /var/log/nginx/
    owner: nginx
    group: nginx
    mode: 0644
  tags: nginx


- name: Change permission of /var/log/nginx/error.log
  sudo: yes
  file:
    state: file
    path: /var/log/nginx/error.log
    owner: nginx
    group: nginx
    mode: 0644
  tags: nginx


- name: Enable nginx
  sudo: yes
  service:
    name: nginx
    enabled: yes
  tags: nginx


- name: Put nginx.conf file
  sudo: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: 0644
  tags: nginx


- name: Restart nginx
  sudo: yes
  service:
    name: nginx
    state: restarted
  tags: nginx
