---
- hosts: vagrant
  remote_user: '{{ user_name }}'
  tasks:
    - name: Git pull master repository
      git:
        repo: '{{ git_repository }}'
        dest: '{{ app_path }}'
        accept_hostkey: yes
        version: master
        force: yes
